name: check

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  check:
    env:
      TEST_ENABLE_WITH_GO: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [11, 17]
        #java_version: [11, 17, 19] # https://github.com/yskszk63/jnhttp-multipartformdata-bodypublisher/actions/runs/3220207710/jobs/5266613356
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java_version }}
        distribution: temurin
        cache: maven
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - run: mvn formatter:validate
    - run: mvn test
    - run: mvn package

  cov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: temurin
        cache: maven
    - run: mvn test
    - uses: codecov/codecov-action@v1.5.0

# vim: set sw=2 ts=2 sts=2:
