name: doc

on:
  push:
    branches:
    - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: temurin
        cache: maven
    - run: mvn javadoc:javadoc
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/apidocs

# vim: set sw=2 ts=2 sts=2:

